### PR TITLE
FIX Password Reset Flow in SupaEmailAuth

### LINKED ISSUE #88: Incomplete "Forgot your password" feature
# Bug report

## Describe the bug

When you try to reset the password the form is unreactive. If you go back to the sign in page, the sign in button is locked and "spinning" 

## To Reproduce

Just setup Supabase as per docs: 

``` dart
await Supabase.initialize(
    url: <URL>,
    anonKey: <AnonKey>,
  );
```

and place in your app a simple auth widget: 

```dart
SupaEmailAuth(
    onSignInComplete: (response) {
      // do something, for example: navigate('home');
    },
    onSignUpComplete: (response) {
      // do something, for example: navigate("wait_for_email");
    },
  ),
```

and make sure that a user exists in the database.

Then:

1. Display the widget
2. Click on 'Forgot your password?'
3. Write the user email
4. Click on 'Send password reset email'
5. Visually nothing happens (command is sent under the hoods)
6. Click on 'Back to sign in'
7. The sign in button is disabled an shows an spinner

## Expected behavior

The password reset command is sent, an snackbar is shown and the widget displays the Sign In form again.

## Screenshots

Captura de pantalla 2024-04-18 a las 11 19 29

## System information

- OS: macOS Sonoma
- Platform: macOS / Web+Chrome 
- supabase_flutter: ^2.5.1
- supabase_auth_ui: ^0.4.4

## Additional context

Maybe related with #36 ?

### PR DESCRIPTION
**Pull request by henry2man**
## What kind of change does this PR introduce?

FIXES #88 

## What is the current behavior?

Password reset flow is incomplete in `SupaEmailAuth`

## What is the new behavior?

Successful password reset flow

## Additional context

N/A

### CODE REVIEW

**Comment by henry2man** [comment]
Added `mounted` guards to avoid the usage of BuildContext's across async gaps

**Comment by henry2man** [comment]
Yeah, second attempt! I was using an older flutter version that didn't trigger the new warnings. Now with `3.19.6` it's working without issues: 

```sh
% fvm flutter --version
Flutter 3.19.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 54e66469a9 (2 days ago) • 2024-04-17 13:08:03 -0700
Engine • revision c4cd48e186
Tools • Dart 3.3.4 • DevTools 2.31.1

% fvm flutter analyze --fatal-warnings --fatal-infos lib
Analyzing lib...                                                
No issues found! (ran in 0.7s)
```

@dshukertjr Why don't you use `fvm`?

**Comment by henry2man** [comment]
Can anyone take a look here? Thanks ❤️

**Review by dshukertjr — APPROVED** [review]
Sorry for the delay. Thanks for the contribution here!

**Comment by henry2man** [comment]
@dshukertjr You're welcome. I still miss some features here (add more possibilities to SignUp flow, more UI tweaks, #32...) so probably I will make more PR in the near future.

**Pull request merged**
