### PR TITLE
chore: publish v0.4.0

### PR DESCRIPTION
**Pull request by dshukertjr**

### CODE REVIEW

**Comment by dshukertjr** [comment]
Want to include https://github.com/supabase-community/flutter-auth-ui/pull/65 if possible, so will update this PR if https://github.com/supabase-community/flutter-auth-ui/pull/65 is merged.

**Review by FatumaA — APPROVED** [review]

**Comment by FatumaA** [comment]
How are we deciding the version numbers?

**Comment by dshukertjr** [comment]
@FatumaA 
I'm following the [semantic versioning](https://semver.org/). Semantic versioning for v0 is a bit weird for Dart. 

You can find the following in [Dart package versioning guide](https://dart.dev/tools/pub/versioning#semantic-versions)

>Although semantic versioning doesn’t promise any compatibility between versions prior to 1.0.0, the Dart community convention is to treat those versions semantically as well. The interpretation of each number is just shifted down one slot: going from 0.1.2 to 0.2.0 indicates a breaking change, going to 0.1.3 indicates a new feature, and going to 0.1.2+1 indicates a change that doesn’t affect the public API. For simplicity’s sake, avoid using + after the version reaches 1.0.0.

So for v0, the versioning is `0.major.minor + patch`. Since the version of this PR contains a breaking change, I'm incrementing major version and going from `0.3.0` to `0.4.0`!

**Comment by FatumaA** [comment]
__

> @FatumaA I'm following the [semantic versioning](https://semver.org/). Semantic versioning for v0 is a bit weird for Dart.
> 
> You can find the following in [Dart package versioning guide](https://dart.dev/tools/pub/versioning#semantic-versions)
> 
> > Although semantic versioning doesn’t promise any compatibility between versions prior to 1.0.0, the Dart community convention is to treat those versions semantically as well. The interpretation of each number is just shifted down one slot: going from 0.1.2 to 0.2.0 indicates a breaking change, going to 0.1.3 indicates a new feature, and going to 0.1.2+1 indicates a change that doesn’t affect the public API. For simplicity’s sake, avoid using + after the version reaches 1.0.0.
> 
> So for v0, the versioning is `0.major.minor + patch`. Since the version of this PR contains a breaking change, I'm incrementing major version and going from `0.3.0` to `0.4.0`!

Thank you! I will read up on this

**Pull request merged**
