### PR TITLE
chore: clean and optimise ui 

### PR DESCRIPTION
**Pull request by FatumaA**

### CODE REVIEW

**Comment by FatumaA** [comment]
@dshukertjr i think i made a mistake and this is a duplicate of #14. 
please delete one

**Comment by FatumaA** [comment]
also, I'm done with the phone auth flow but you will need to also test it

**Comment by dshukertjr** [comment]
@FatumaA Nice! I will test out the phone auth!

**Comment by dshukertjr** [comment]
Oh, wait, I just noticed that phone auth is not included in this PR 😂 I will try to resolve the conflicts and merge this one!

**Review by dshukertjr — APPROVED** [review]
Thanks for the amazing work!

**Comment by dshukertjr** [comment]
Wait, I was obviously not paying attention to the details 😂 I see the phone auth method! I will test it out!

**Pull request merged**
