### PR TITLE
Fix autofill not opening when tapping on email field in SupaEmailAuth

### LINKED ISSUE #79: The email sign in autocomplete is not applied to the entire form
# Bug report

## Describe the bug

SupaEmailAuth only prompts for autofill on the password field 

## To Reproduce

Use SupaEmailAuth, tap into the email field.

## Expected behavior

The app should propt the keyboard for autofill credentials and subsequently show the user configured autofill flow.

## System information

Android 14
supabase_auth_ui: ^0.4.3
Flutter: Channel stable, 3.19.3

## Additional context

The problem arises because SupaEmailAuth [does not wrap the Form in an AutofillGroup](https://github.com/supabase-community/flutter-auth-ui/blob/main/lib/src/components/supa_email_auth.dart#L136).

### PR DESCRIPTION
**Pull request by pohuing**
## What kind of change does this PR introduce?

Adds an AutofillGroup to the email sign in form

## What is the current behavior?

Fixes #79 

## What is the new behavior?

Activating the email field will now propt for autofill data, selecting an entry from the password field will also fill the email field.

### CODE REVIEW

**Review by dshukertjr — COMMENTED** [review]
Thanks for this. So this PR just pretty much wraps the Form with a AutoFillGroup, correct? 

It seems like there is a formatting issue, but would you be able to take care of that?

**Comment by pohuing** [comment]
> Thanks for this. So this PR just pretty much wraps the Form with a AutoFillGroup, correct?

exactly.

I'll see if I can figure out what went wrong with the formatting tomorrow. I use dartfmt on save, so maybe our styles are clashing.

**Comment by pohuing** [comment]
Nothing went wrong as far as I can tell. Since the Form is wrapped in another Widget it's just indented one more layer. Combined with moving the content down one line Github gets very confused detecting changes.

I'll add the same changes to the PhoneAuth Widget as well, since it's the same kind of identifier+password combo

**Comment by pohuing** [comment]
> Nothing went wrong as far as I can tell. Since the Form is wrapped in another Widget it's just indented one more layer. Combined with moving the content down one line Github gets very confused detecting changes.

Ignore this, I didn't even notice the action fail.

**Review by dshukertjr — APPROVED** [review]
LGTM! Thanks for an amazing update!

**Pull request merged**
