### PR TITLE
fix: add github actions and fix errors in example

### PR DESCRIPTION
**Pull request by dshukertjr**

### CODE REVIEW

**Review by FatumaA — APPROVED** [review]

**Comment by FatumaA** [comment]
@dshukertjr could you enable discussions? I wanted to write out a list of things that need to be cleaned up/done so that we dont end up doing the same thing. Also, so we have a reference point for what we are doing

**Comment by dshukertjr** [comment]
@FatumaA 
Would issues be good to track things that needs to be done?

**Comment by FatumaA** [comment]
Not sure  maybe like a brain dump of sorts? For tracking, maybe the projects section of github?

**Comment by dshukertjr** [comment]
@FatumaA 
I think the issues would be the perfect place to dump out all the potential ideas that we want to implement!

**Comment by dshukertjr** [comment]
I will add a few that comes to my mind to get us started!

**Comment by FatumaA** [comment]
Perfect then.
I wont be able to get set up for a bit so you can start whenever you are ready

**Pull request merged**
